### ISSUE TITLE
'RequestCookieJar' object has no attribute 'load'

### ISSUE THREAD

**Issue by kjabl** [marzzzello/pytr#24]
**Description of the bug**
After upgrading to 0.1.0 weblogin doesn't work anymore.

**To Reproduce**

1. Go to 'terminal'
2. Ran the command `pytr login` or `pytr dl_docs .`
3. Do 'Enter phone number and pin when asked to'

**Expected behavior**
Pytr performs login and downloads documents

**Error log**

```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\pytr-script.py", line 33, in <module>
    sys.exit(load_entry_point('pytr==0.1.0', 'console_scripts', 'pytr')())
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\main.py", line 143, in main
    login(phone_no=args.phone_no, pin=args.pin, web=weblogin)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\account.py", line 66, in login
    if tr.resume_websession():
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\api.py", line 226, in resume_websession
    self._websession.cookies.load(ignore_discard=True, ignore_expires=True)
AttributeError: 'RequestsCookieJar' object has no attribute 'load'
```

**Environment**

- OS: Windows 10
- pytr version: 0.1.0

**Additional context**
0.0.18 worked before. Anything I did was updating pytr by calling `pip install --upgrade pytr`

**Comment by marzzzello** [comment]
Looks like you had a cookies.txt file in ~/.pytr but no credentials file. Is that correct?

This case will not appear in the future now that #20 is fixed
Just delete the cookies.txt and it should work

**Comment by marzzzello** [comment]
I added a fix in 0.1.1 too

**Comment by kjabl** [comment]
Sorry for the late reply. Your asseumption was correct. I had a cookies.txt file, deleted it and now it works.
